repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--exclude, "sdk/llm_obs_tests"]
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - sqlalchemy
          - types-redis
          - fastapi
          - types-python-jose
          - types-passlib
          - types-python-dateutil
          - structlog
          - httpx
          - taskiq
          - taskiq-redis
          - aiosmtplib
          - prometheus-client
          - "types-aioboto3[s3]"
          - alembic
          - pytest
          - respx
          - locust
          - prometheus-fastapi-instrumentator
          - opentelemetry-proto

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
