"""add_alert_tables

Revision ID: f37d7ee64540
Revises: 891391a704b3
Create Date: 2026-05-29 12:21:20.823908

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f37d7ee64540"
down_revision: str | Sequence[str] | None = "891391a704b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("metric", sa.String(length=50), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("threshold", sa.Numeric(), nullable=True),
        sa.Column("window_minutes", sa.Integer(), nullable=False),
        sa.Column("notify_slack_webhook", sa.String(length=500), nullable=True),
        sa.Column("notify_email", sa.String(length=255), nullable=True),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IN ('gt','lt','anomaly')", name="ck_alert_rules_condition"
        ),
        sa.CheckConstraint(
            "metric IN ('latency_p95','error_rate','cost_hourly','anomaly')",
            name="ck_alert_rules_metric",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alert_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column(
            "triggered_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alert_events", "alert_events", ["rule_id", sa.text("triggered_at DESC")]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("idx_alert_events", table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_table("alert_rules")
    # ### end Alembic commands ###
